# Generated by Django 5.1.4 on 2025-01-01 13:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_h2h', max_length=255, null=True, verbose_name='image'),
        ),
    ]
