# Generated by Django 5.1.4 on 2024-12-30 15:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_h2h', max_length=255, null=True, verbose_name='image'),
        ),
    ]
