# Generated by Django 5.1.4 on 2025-01-01 13:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_h2h', max_length=255, null=True, verbose_name='image'),
        ),
    ]
